### ISSUE TITLE
Wrong test format

### ISSUE THREAD

**Issue by rockwyc992** [rockwyc992/monkey-pdns#1]
Sorry, I use the different format of "hello, world" in `templates/hello.html` and `test.py`

```
FAIL: test_hello (monkey_pdns.app.tests.View_hello_tests)
    AssertionError: False is not true : Couldn't find 'Hello, world.' in response
```

**Comment by chuanchan1116** [comment]
Resolved. See commit [`b041372`](https://github.com/rockwyc992/monkey-pdns/commit/b041372b16faaec4cf88b4969493834d27ec388f)
